(function(){var f=null;var h=function(a,b){for(var e in a)Object.prototype.hasOwnProperty.call(a,e)&&b.call(f,a[e],e,a)};var l=function(a){this.b=[];this.a={};for(var b=0,e=arguments.length;b<e;++b)this.a[arguments[b]]=""};l.prototype.c=function(a){return this.a.hasOwnProperty(a)?this.a[a]:""};l.prototype.geil=l.prototype.c;var p=function(){var a=m,b=[];h(a.a,function(a){""!=a&&b.push(a)});return 0<a.b.length&&0<b.length?a.b.join(",")+","+b.join(","):a.b.join(",")+b.join(",")};var m,r="google_conversion_id google_conversion_format google_conversion_type google_conversion_order_id google_conversion_language google_conversion_value google_conversion_domain google_conversion_label google_conversion_color google_disable_viewthrough google_remarketing_only google_remarketing_for_search google_conversion_items google_custom_params google_conversion_date google_conversion_time google_conversion_js_version onload_callback opt_image_generator google_is_call google_conversion_page_url".split(" ");
function t(a){return a!=f?escape(a.toString()):""}function u(a,b){var e=t(b);if(""!=e){var c=t(a);if(""!=c)return"&".concat(c,"=",e)}return""}function v(a){var b=typeof a;return a==f||"object"==b||"function"==b?f:String(a).replace(/,/g,"\\,").replace(/;/g,"\\;").replace(/=/g,"\\=")}
function w(a){var b;a=a.google_custom_params;if(!a||"object"!=typeof a||"function"==typeof a.join)b="";else{var e=[];for(b in a)if(Object.prototype.hasOwnProperty.call(a,b)){var c=a[b];if(c&&"function"==typeof c.join){for(var d=[],g=0;g<c.length;++g){var k=v(c[g]);k!=f&&d.push(k)}c=0==d.length?f:d.join(",")}else c=v(c);(d=v(b))&&c!=f&&e.push(d+"="+c)}b=e.join(";")}return""==b?"":"&".concat("data=",encodeURIComponent(b))}
function x(a){return"number"!=typeof a&&"string"!=typeof a?"":t(a.toString())}function z(a){if(!a)return"";a=a.google_conversion_items;if(!a)return"";for(var b=[],e=0,c=a.length;e<c;e++){var d=a[e],g=[];d&&(g.push(x(d.value)),g.push(x(d.quantity)),g.push(x(d.item_id)),g.push(x(d.adwords_grouping)),g.push(x(d.sku)),b.push("("+g.join("*")+")"))}return 0<b.length?"&item="+b.join(""):""}
function A(a,b,e){var c=[];if(a){var d=a.screen;d&&(c.push(u("u_h",d.height)),c.push(u("u_w",d.width)),c.push(u("u_ah",d.availHeight)),c.push(u("u_aw",d.availWidth)),c.push(u("u_cd",d.colorDepth)));a.history&&c.push(u("u_his",a.history.length))}e&&"function"==typeof e.getTimezoneOffset&&c.push(u("u_tz",-e.getTimezoneOffset()));b&&("function"==typeof b.javaEnabled&&c.push(u("u_java",b.javaEnabled())),b.plugins&&c.push(u("u_nplug",b.plugins.length)),b.mimeTypes&&c.push(u("u_nmime",b.mimeTypes.length)));
return c.join("")}function B(a,b,e){var c="";if(b){var c=c+u("ref",b.referrer!=f?b.referrer.toString().substring(0,256):""),d;if(a.top==a)d=0;else if(b=a.location.ancestorOrigins)d=b[b.length-1]==a.location.origin?1:2;else{b=a.top;try{d=!!b.location.href||""===b.location.href}catch(g){d=!1}d=d?1:2}b="";b=e?e:1==d?a.top.location.href:a.location.href;c+=u("url",b!=f?b.toString().substring(0,256):"");c+=u("frm",d)}return c}
function C(a){return a&&a.location&&a.location.protocol&&"https:"==a.location.protocol.toString().toLowerCase()?"https:":"http:"}function D(){return new Image}function E(a,b,e){var c=D;"function"===typeof a.opt_image_generator&&(c=a.opt_image_generator);c=c();b+=u("async","1");c.src=b;c.onload=e&&"function"===typeof a.onload_callback?a.onload_callback:function(){}}
function F(a){for(var b=window,e={},c=function(c){e[c]=a&&a[c]!=f?a[c]:b[c]},d=0;d<r.length;d++)c(r[d]);c("onload_callback");return e};window.google_trackConversion=function(a){a=F(a);a.google_conversion_format=3;var b;var e=window,c=navigator,d=document,g=!1;if(!a||3!=a.google_conversion_format)b=!1;else{try{var k;"landing"==a.google_conversion_type||!a.google_conversion_id||a.google_remarketing_only&&a.google_disable_viewthrough?k=!1:(a.google_conversion_date=new Date,a.google_conversion_time=a.google_conversion_date.getTime(),a.google_conversion_snippets="number"==typeof a.google_conversion_snippets&&0<a.google_conversion_snippets?
a.google_conversion_snippets+1:1,"number"!=typeof a.google_conversion_first_time&&(a.google_conversion_first_time=a.google_conversion_time),a.google_conversion_js_version="7",0!=a.google_conversion_format&&(1!=a.google_conversion_format&&2!=a.google_conversion_format&&3!=a.google_conversion_format)&&(a.google_conversion_format=1),m=new l(1),k=!0);if(k){k="/?";"landing"==a.google_conversion_type&&(k="/extclk?");var G=C(e)+"//"+(a.google_remarketing_only?"googleads.g.doubleclick.net":a.google_conversion_domain||
"www.googleadservices.com")+"/pagead/"+[a.google_remarketing_only?"viewthroughconversion/":"conversion/",t(a.google_conversion_id),k,"random=",t(a.google_conversion_time)].join(""),q;e:{var y=a.google_conversion_language;if(y!=f){var n=y.toString();if(2==n.length){q=u("hl",n);break e}if(5==n.length){q=u("hl",n.substring(0,2))+u("gl",n.substring(3,5));break e}}q=""}b=[u("cv",a.google_conversion_js_version),u("fst",a.google_conversion_first_time),u("num",a.google_conversion_snippets),u("fmt",a.google_conversion_format),
u("value",a.google_conversion_value),u("label",a.google_conversion_label),u("oid",a.google_conversion_order_id),u("bg",a.google_conversion_color),q,u("guid","ON"),u("disvt",a.google_disable_viewthrough),u("is_call",a.google_is_call),z(a),A(e,c,a.google_conversion_date),B(e,d,a.google_conversion_page_url),w(a),a.google_remarketing_for_search&&!a.google_conversion_domain?"&srr=n":"",u("eid",p())].join("");E(a,G+b,!0);if(a.google_remarketing_for_search&&!a.google_conversion_domain){var s=C(e)+"//www.google.com/ads/user-lists/"+
[t(a.google_conversion_id),"/?random=",Math.floor(1E9*Math.random())].join(""),s=s+[u("label",a.google_conversion_label),u("fmt","3"),B(e,d,a.google_conversion_page_url)].join("");E(a,s,!1)}g=!0}}catch(H){}b=g}return b};})();
